---
title: "Ejemplos de Tidyverse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparativo 

## Carga de paquetes 
```{r librerias, message=FALSE}  
# dplyr
library(dplyr)

# ggplot2
library(ggplot2)
```

## Carga de datos

```{r datos}
#datos rios
rios <-
  read.csv(file = 'https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/hidrologia/fdc/fdc.csv')

#datos covid
covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )
```


## dplyr

### mutate ()

```{r}
#estructura del data frame
str(rios)
```


```{r}
# despliegue los primeros registros
slice_head(rios,n=10)

# despliegue los últimos registros
slice_tail(rios,n=10)

# despliegue registros al azar
slice_sample(rios,n=10)

```

```{r}
#funciones enlazadas
rios %>%slice_head(n = 10) %>% slice_tail(n = 2)
```

```{r}
#funciones anidadas
slice_tail(slice_head(rios, n = 10), n = 2)
```

```{r}
#Cambio nombre de las columnas mediante rename
rios <- rios %>% 
  rename(fecha = Tiempo,
         pandora = Pandora.mm..637km2.,
         banano = Banano.mm..90km2.)
rios <- rios %>% 
  mutate (fecha = as.Date(fecha, format = "%m/%d/%Y"),
          promedio = (pandora + banano)/2)

slice_head(rios, n = 10)
```
## Graficos 

## Histograma 

```{r rios_histograma}
# Histograma simple

rios %>%
  ggplot(aes(x = pandora)) +
  geom_histogram()

# Histograma simple

rios %>%
  ggplot(aes(x = pandora)) +
  geom_histogram(binwidth = 1,
                 color = "black",
                 fill = "white")

```

### gráfico de lineas

```{r rios-lineas}
# Gráfico de líneas simple

rios %>%
  ggplot(aes (x=fecha, y = pandora))+
  geom_line()
```


### select ()

```{r}
covid_columnas_seleccionadas <-
  covid %>%
  select(FECHA, muj_posi, hom_posi) %>%
  rename(
    fecha = FECHA,
    positivos_mujeres = muj_posi,
    positivos_hombres = hom_posi
  ) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))

slice_head(covid_columnas_seleccionadas, n = 10)
```

### filter()

```{r}
# Selección, renombramiento, conversión de columnas y filtrado
covid_filtrado <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  filter(positivos_nuevos >= 2500)

# Despliegue del data frame con los resultados
covid_filtrado
```
### arrange () 
```{r ejemplos-arrange}
covid_filtrado_ordenado_x_positivos_nuevos <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  filter(positivos_nuevos >= 2500) %>%
  arrange(desc(positivos_nuevos))

# Despliegue del data frame con los resultados
#covid_filtrado_ordenado_x_positivos_nuevos
slice_head(covid_filtrado_ordenado_x_positivos_nuevos, n = 10)
```

### summarise() 
```{r ejemlos-summarise-01}
# Selección, renombramiento, filtrado y conversión de columnas
covid_positivos_nuevos_sumarizado_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(anio = format(fecha,"%Y"), mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = sum(positivos_nuevos))

# Despliegue del data frame con los resultados
covid_positivos_nuevos_sumarizado_x_mes


```


```{r ejemlos-summarise-03}
# Selección, renombramiento, filtrado y conversión de columnas
covid_positivos_nuevos_sumarizado_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = sum(positivos_nuevos))

# Despliegue del data frame con los resultados
covid_positivos_nuevos_sumarizado_x_mes
```

```{r ejemlos-summarise-04}
# promedio de casos nuevos por mes
covid_positivos_nuevos_promedio_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(mes = format(fecha,"%m")) %>%
  summarise(promedio_positivos = mean(positivos_nuevos))

# Despliegue del data frame con los resultados
covid_positivos_nuevos_promedio_x_mes
```

